# Workflow for testing Spoon.
#
# Note that actions are specified by commit hash. This is to avoid the security
# risk of someone injecting malicious code into a release and then simply
# changing a tag.

name: tests
on:
  workflow_dispatch:
env:
  MAVEN_OPTS: >-
    -Dmaven.resolver.transport=native
    -Daether.connector.connectTimeout=300000
    -Daether.connector.requestTimeout=300000
  NIX_OPTIONS: >-
    --ignore-environment
    --keep MAVEN_OPTS --keep PATH --keep LANG

jobs:
  test-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
          arch: arm64
          runner: macos-latest
          java-distribution: temurin
          java-version: '17.0.20+101'
          expander_leg: macos-latest--arm64
    runs-on: ${{ matrix.runner }}
    name: Tests with Java 17 on windows-latest [${{ matrix.expander_leg }}]
    steps:
    - name: Disable Git's autocrlf
      run: git config --global core.autocrlf false
    - name: git checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1   # v7.0.1
      with:
        fetch-depth: 0
    - uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6   # v6
      with:
        distribution: ${{ matrix.java-distribution }}
        java-version: ${{ matrix.java-version }}
        architecture: ${{ matrix.arch }}
        cache: 'maven'

    - name: Test
      run: |
        cp chore/logback.xml src/test/resources/
        mvn -f spoon-pom test
        cat testResults.spoon

    timeout-minutes: 150
